#!/usr/bin/env python3
from subprocess import Popen, PIPE, STDOUT
from regenConf import regen as regenNginxConfiguration

regenNginxConfiguration()
Popen(['/usr/sbin/nginx'], stdout=PIPE, stderr=STDOUT)