#!/usr/bin/env python3
import os
import sys
import signal
sys.path.insert(1, os.path.join(sys.path[0], '..'))
from regenConf import regen as regenNginxConfiguration
from subprocess import PIPE, Popen, STDOUT
from livePrintStdout import livePrintStdout

def onSignal(signum, stack):
    print('Received signal {}.'.format(signal.Signals(signum).name))
    foregroundNginxProcess.terminate()

regenNginxConfiguration()
foregroundNginxProcess = Popen(['/usr/sbin/nginx', '-g', 'daemon off;'], stdout=PIPE, stderr=STDOUT)
signal.signal(signal.SIGTERM, onSignal)
signal.signal(signal.SIGINT, onSignal)
livePrintStdout(foregroundNginxProcess)