#!/usr/bin/env python3
from subprocess import PIPE, Popen, STDOUT
from livePrintStdout import livePrintStdout
from regenConf import regen as regenNginxConfiguration

regenNginxConfiguration()
livePrintStdout(Popen(['/usr/sbin/nginx', '-s', 'reload'], stdout=PIPE, stderr=PIPE))