#!/usr/bin/env python3
import os
from certCheck import CertCheck
from certbot import run
from loadEnv import load as loadEnvVariables
from printSubprocessStdout import printSubprocessStdout
from subprocess import check_output

def relative(subpath):
    return os.path.join(os.path.dirname(__file__), subpath)

print('Cert check cron job started.')
loadEnvVariables()
print('Loaded environment variables.')

certCheck = CertCheck()
if certCheck.shouldServerUpdate():
	print('Saved timestamp is older than at least one of certificate files or there is no saved timestamp yet. Using newest certificate files by reloading the server.')
	printSubprocessStdout(message=check_output(relative('server/reloadServer')), colors=False)
	print('Server reload requested.')
	certCheck.updateTimestamp()
else:
	print('No action required.')
print('Cert check cron job finished.')