#!/usr/bin/env python3
from certCheck import CertCheck
from loadEnv import load as loadEnvVariables
from printSubprocessStdout import printSubprocessStdout
from subprocess import check_output

def relative(subpath='', useCwd=False):
	import os
	basePath = os.getcwd() if useCwd else os.path.dirname(os.path.abspath(__file__))
	return os.path.normpath(os.path.join(basePath, os.path.expanduser(subpath)))

print('Cert check cron job started.')
loadEnvVariables()
print('Loaded environment variables.')

certCheck = CertCheck()
if certCheck.shouldServerUpdate():
	print('Saved timestamp is older than at least one of certificate files or there is no saved timestamp yet. Using newest certificate files by reloading the server.')
	printSubprocessStdout(message=check_output(relative('server/reloadServer')), colors=False)
	print('Server reload requested.')
	certCheck.updateTimestamp()
else:
	print('No action required.')
print('Cert check cron job finished.')